title: 龍門居
author: 龍門居業主立案法團
email: oasislungmun@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  龍門居業主立案法團
show_excerpts: true # set to true to show excerpts on the homepage
#baseurl: /path

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title:  龍門居
  tagline: 業主立案法團
  date_format: "%b %-d, %Y"
  style: pink
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    #facebook: LungMunOasis
    #twitter: 
    #github:  
    #linkedIn: 
    #rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed